version: '3'
services:
  web:
    build: ./packages/web 
    command: npm start
    volumes:
      - ./packages/web:/code
    ports:
      - 8080:8080
      - 3000:3000
    environment:
      NODE_PORT: 8080
  redis:
    image: "redis:3.2.11-alpine"
    ports:
      - 6379:6379
  cache-service:
    build: ./packages/cache-service
    command: npm start
    volumes:
      - ./packages/cache-service:/code
    ports:
      - 443:8080
    environment:
      NODE_PORT: 8080
